// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpdcvekfpjgzjiletqek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZGN2ZWtmcGpnemppbGV0cWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjE2MDIsImV4cCI6MjA2MDczNzYwMn0.-8qW_8rQuk_gYmAm6pwBuvLiCeNsqqFiUehAjun05sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);